version: 0.1
log:
  level: info
storage:
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
http:
  addr: :5000
proxy:
  remoteurl: https://registry-1.docker.io
compatibility:
  schema1:
    enabled: false
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
